language: php
dist: trusty

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  include:
    - php: 7.0
      env: COMPOSER_REQUIRE="symfony/process:^2.0"
    - php: 7.0
      env: COMPOSER_REQUIRE="symfony/process:^3.0"
    - php: 7.2
      env: COMPOSER_REQUIRE="symfony/process:^5.0"
    - php: 7.3
      env: COMPOSER_REQUIRE="symfony/process:^5.0"

before_script:
  - composer self-update
  - if [ -n "$COMPOSER_REQUIRE" ]; then composer require --no-update $COMPOSER_REQUIRE; fi
  - composer update $COMPOSER_OPTIONS
